// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz0GDgwB5nZy5LO1uh8WjM_Rp8W89E-PA',
    appId: '1:87186500702:web:246bec6bc90e35431018cf',
    messagingSenderId: '87186500702',
    projectId: 'mentora-e9075',
    authDomain: 'mentora-e9075.firebaseapp.com',
    storageBucket: 'mentora-e9075.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChKudt5t075sO8wBGOGeexquqV24zX8bs',
    appId: '1:87186500702:android:dbc8dcfcdf4e6a001018cf',
    messagingSenderId: '87186500702',
    projectId: 'mentora-e9075',
    storageBucket: 'mentora-e9075.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs8ps3UeqwdrryLhabVngreoan6z0avJ4',
    appId: '1:87186500702:ios:7620b6375398c46b1018cf',
    messagingSenderId: '87186500702',
    projectId: 'mentora-e9075',
    storageBucket: 'mentora-e9075.firebasestorage.app',
    iosBundleId: 'com.example.studyAssistent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs8ps3UeqwdrryLhabVngreoan6z0avJ4',
    appId: '1:87186500702:ios:7620b6375398c46b1018cf',
    messagingSenderId: '87186500702',
    projectId: 'mentora-e9075',
    storageBucket: 'mentora-e9075.firebasestorage.app',
    iosBundleId: 'com.example.studyAssistent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDz0GDgwB5nZy5LO1uh8WjM_Rp8W89E-PA',
    appId: '1:87186500702:web:19f67edaa4afc7e41018cf',
    messagingSenderId: '87186500702',
    projectId: 'mentora-e9075',
    authDomain: 'mentora-e9075.firebaseapp.com',
    storageBucket: 'mentora-e9075.firebasestorage.app',
  );
}
